# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateDeltaHat <- function(sData, batches) {
    .Call('sva_calculateDeltaHat', PACKAGE = 'sva', sData, batches)
}

parametricAdjust <- function(sDat, gammaHat, deltaHat, gammaBar, t2, aPrior, bPrior, batches, numBatches, conv = 0.0001) {
    .Call('sva_parametricAdjust', PACKAGE = 'sva', sDat, gammaHat, deltaHat, gammaBar, t2, aPrior, bPrior, batches, numBatches, conv)
}

nonparametricAdjust <- function(sDat, gammaHatMatrix, deltaHatMatrix, batches, numBatches) {
    .Call('sva_nonparametricAdjust', PACKAGE = 'sva', sDat, gammaHatMatrix, deltaHatMatrix, batches, numBatches)
}

